### ISSUE TITLE
no toc is being generated for lecture

### ISSUE THREAD

**Issue by mattisebastian** [TUD-INF-IAI-MCI/AgsbsMarkdownPlugin#10]
For the current lecture of Datenbankprogrammierung there is no table of content generated, the inhalt.md ist just empty. 
To reproduce, just checkout the version and press F6.

**Comment by humenda** [comment]
This is an error in the material you're editing. The toc-depth is set to one, while all headings in the material are level 2. Furthermore, but not related to this problem, the naming of the files/directories is wrong. Please fix that in the material. Thanks.
